### ISSUE TITLE
Commit latest changes (Version: 2.6.6)

### ISSUE THREAD

**Issue by ATouhou** [solmri/wizmage#2]
Hi.
Thanks for this wonderfull plugin. Could you please commit your latest changes ( Version: 2.6.6 )as live on Google Store.

**Comment by solmri** [comment]
Hello

Thanks for writing back. I apologize for writing back so late. I do not actively maintain the project, so the requests can be kind of delayed. 

I'd update it soon. 

Thanks
[m]

**Comment by ATouhou** [comment]
Thanks! Sounds good :-)

**Comment by ATouhou** [comment]
https://app.assembla.com/spaces/wizmage/subversion/source
