### ISSUE TITLE
Google store

### ISSUE THREAD

**Issue by ATouhou** [solmri/wizmage#3]
It's no longer available on google store. Why?

**Comment by shlgug** [comment]
It is available here:  https://chrome.google.com/webstore/detail/wizmage-image-hider/ifoggbfaoakkojipahnplnbfnhhhnmlp?hl=en
The code is being maintained by the original author here:  https://app.assembla.com/spaces/wizmage/subversion/source

**Comment by ATouhou** [comment]
Thanks @shlgug  :-)

**Comment by shlgug** [comment]
The original author just posted his code on github and is planning on maintaining his code on github going forward.  Here is the link:  https://github.com/elicym/wizmage
